database:
  host: localhost
  dbname: kunpengsecl
  port: 5432
  user: "postgres"
  password: "postgres"
rasconfig:
  port: "127.0.0.1:40001"
  rest: "127.0.0.1:40002"
  changetime: 0
  mgrstrategy: auto
  authkeyfile: ./ecdsakey.pub
  basevalue-extract-rules:
    pcrinfo:
      pcrselection: [1, 2, 3, 4]
    manifest:
      - type: bios
        name: ["8-0", "2147483656-1"]
      - type: ima
        name: ["boot_aggregate", "/etc/modprobe.d/tuned.conf"]
racconfig:
  hbduration: 5s
  trustduration: 2m0s
  digestalgorithm: sha256
