database:
  dbname: kunpengsecl
  host: localhost
  password: postgres
  port: 5432
  user: postgres
log:
  path: ./ras-log.txt
racconfig:
  digestalgorithm: sha256
  hbduration: 5s
  trustduration: 10s
rasconfig:
  authkeyfile: ./ecdsakey.pub
  auto-update-config:
    isallupdate: false
    updateclients:
    - 1
  basevalue-extract-rules:
    manifest:
    - name:
      - 8-0
      - 80000008-1
      type: bios
    - name:
      - boot_aggregate
      - /etc/modprobe.d/tuned.conf
      type: ima
    pcrinfo:
      pcrselection:
      - 1
      - 2
      - 3
      - 4
  changetime: 2022-07-10T22:39:50.6083338+08:00
  mgrstrategy: manual
  pcakeycertfile: ./pca-ek.crt
  pcaprivkeyfile: ./pca-ek.key
  port: 127.0.0.1:40001
  rest: 0.0.0.0:40002
  rootkeycertfile: ./pca-root.crt
  rootprivkeyfile: ./pca-root.key
