database:
  dbname: kunpengsecl
  host: localhost
  password: postgres
  port: 5432
  user: postgres
log:
  path: ./ras-log.txt
racconfig:
  digestalgorithm: "sha1"
  hbduration: 5s
  trustduration: 2m0s
rasconfig:
  authkeyfile: ./ecdsakey.pub
  auto-update-config:
    isallupdate: false
    updateclients: []
  basevalue-extract-rules:
    manifest:
    - name:
      - 8-0
      - 80000008-1
      type: bios
    - name:
      - boot_aggregate
      - /etc/modprobe.d/tuned.conf
      type: ima
    pcrinfo:
      pcrselection:
      - 1
      - 2
      - 3
      - 4
  changetime: 1970-01-01T08:00:00+08:00
  mgrstrategy: auto
  pcakeycertfile: ./pca-ek.crt
  pcaprivkeyfile: ./pca-ek.key
  port: 127.0.0.1:40001
  rest: 127.0.0.1:40002
  rootkeycertfile: ./pca-root.crt
  rootprivkeyfile: ./pca-root.key
