kaconfig:
  ccfile: ./cert/ca.crt
  kcfile: ./cert/kta.crt
  kkeyfile: ./cert/kta.key
  ktapath: /root/data/435dcafa-0029-4d53-97e8-a7a13a80c82e.sec
  pollduration: 1s
log:
  path: ./rac-log.txt
racconfig:
  clientid: -1
  digestalgorithm: sha1
  ecfile: ""
  ectestfile: ""
  hbduration: 5s
  icfile: ""
  ictestfile: ""
  password: ""
  seed: -1
  server: 127.0.0.1:40001
  trustduration: 2m0s
  qcaserver: 127.0.0.1:40007
