log:
  path: ./rac-log.txt
racconfig:
  clientid: -1
  digestalgorithm: sha1
  ekcerttest: ""
  hbduration: 5s
  ikcerttest: ""
  password: ""
  seed: -1
  server: 127.0.0.1:40001
  trustduration: 2m0s
